# Generated by Django 4.2.16 on 2025-03-08 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetronomeSoundSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_beat_sound', models.FileField(help_text='Sound for the first beat of the measure', upload_to='metronome_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg'])])),
                ('accent_sound', models.FileField(help_text='Sound for accented beats', upload_to='metronome_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg'])])),
                ('normal_beat_sound', models.FileField(help_text='Sound for normal beats', upload_to='metronome_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg'])])),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
