# Generated by Django 4.2.16 on 2025-03-08 20:19

import django.core.validators
from django.db import migrations, models
import metronome_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome_api', '0002_metronomesoundset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metronomesettings',
            options={'verbose_name': 'Metronome Settings', 'verbose_name_plural': 'Metronome Settings'},
        ),
        migrations.AlterModelOptions(
            name='metronomesoundset',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Metronome Sound Set', 'verbose_name_plural': 'Metronome Sound Sets'},
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='accent_sound',
            field=models.FileField(help_text='Sound for accented beats', upload_to='metronome_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg']), metronome_api.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='first_beat_sound',
            field=models.FileField(help_text='Sound for the first beat of the measure', upload_to='metronome_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg']), metronome_api.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='normal_beat_sound',
            field=models.FileField(help_text='Sound for normal beats', upload_to='metronome_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg']), metronome_api.models.validate_audio_file]),
        ),
    ]
