# Generated by Django 4.2.16 on 2025-03-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metronome_api', '0003_alter_metronomesettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetronomeSettings',
        ),
    ]
