# Generated by Django 4.2.16 on 2025-03-09 18:55

import django.core.validators
from django.db import migrations, models
import metronome_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome_api', '0004_delete_metronomesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metronomesoundset',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Metronome Sound Set', 'verbose_name_plural': 'Metronome Sound Sets'},
        ),
        migrations.RemoveField(
            model_name='metronomesoundset',
            name='is_default',
        ),
        migrations.AddField(
            model_name='metronomesoundset',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one sound set can be active at a time.'),
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='accent_sound',
            field=models.FileField(help_text='Sound for accented beats', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg']), metronome_api.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='first_beat_sound',
            field=models.FileField(help_text='Sound for the first beat of the measure', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg']), metronome_api.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metronomesoundset',
            name='normal_beat_sound',
            field=models.FileField(help_text='Sound for normal beats', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg']), metronome_api.models.validate_audio_file]),
        ),
    ]
